version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bus_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount thư mục init-db vào trong container để nó tự chạy các script khởi tạo DB
      - ./infrastructure/init-db:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: bus_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: bus_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"   # Port để các service kết nối nhắn tin
      - "15672:15672" # Port để mở giao diện quản trị trên Web
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./infrastructure/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: bus_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: bus_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./infrastructure/kafka/create-topics.sh:/tmp/create-topics.sh

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
